import type { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'GreenNexa Terms and Conditions — account usage, user responsibilities, AI limitations and acceptable use.',
};

const LAST_UPDATED = 'September 2026';

export default function TermsPage() {
  return (
    <>
      <Header />
      <main>
        <section className={styles.pageHero}>
          <div className="container">
            <span className="section-label">📄 Legal</span>
            <h1 className="section-title">Terms &amp; Conditions</h1>
            <p className={styles.lastUpdated}>Last updated: {LAST_UPDATED}</p>
          </div>
        </section>

        <section className="section">
          <div className="container">
            <div className={styles.legalDoc}>

              <div className={styles.intro}>
                By accessing or using the GreenNexa platform, you agree to these Terms and Conditions.
                If you do not agree, do not use the platform.
              </div>

              <Section title="1. Account Usage">
                <p>
                  You are responsible for maintaining the confidentiality of your login credentials.
                  Do not share your password or organisation credentials. Report any unauthorised access
                  to GreenNexa immediately. Accounts are personal and non-transferable unless explicitly
                  permitted by Super Admin.
                </p>
              </Section>

              <Section title="2. User Responsibilities">
                <ul className={styles.list}>
                  <li>Provide accurate information when creating accounts and organisations.</li>
                  <li>Use the platform only for legitimate facility management purposes.</li>
                  <li>Do not attempt to access data belonging to other organisations.</li>
                  <li>Do not attempt to reverse-engineer, bypass or exploit platform security.</li>
                  <li>Report anomalies in platform behaviour to GreenNexa support.</li>
                  <li>Change temporary passwords promptly after first login.</li>
                </ul>
              </Section>

              <Section title="3. Organisation Responsibilities">
                <p>
                  Organisation administrators are responsible for ensuring that all users added to their
                  organisation comply with these terms. Organisations must only register devices and
                  configure sensors that they are authorised to monitor. Organisations must not use
                  GreenNexa to process data from facilities they do not own or manage.
                </p>
              </Section>

              <Section title="4. IoT Responsibilities">
                <p>
                  If you connect physical IoT devices to GreenNexa, you are responsible for securing
                  those devices and their credentials. Device credentials must not be embedded in
                  public code or front-end applications. You must only send sensor data that represents
                  your authorised facility.
                </p>
              </Section>

              <Section title="5. AI Limitations">
                <p>
                  GreenNexa uses artificial intelligence and machine learning to detect anomalies,
                  generate forecasts and produce recommendations. These outputs are provided as
                  decision-support tools only. They are not guaranteed to be accurate, complete or
                  suitable for any particular purpose. GreenNexa AI results must never be used as
                  the sole basis for critical operational, safety or compliance decisions.
                </p>
              </Section>

              <Section title="6. Forecast Limitations">
                <p>
                  Forecasts generated by GreenNexa are estimates based on historical data patterns.
                  They are clearly labelled as &quot;Estimated / Predicted&quot;. Future values may differ
                  significantly from forecasts due to changes in facility operations, equipment, occupancy
                  or external conditions. GreenNexa makes no warranty regarding forecast accuracy.
                </p>
              </Section>

              <Section title="7. Acceptable Use">
                <ul className={styles.list}>
                  <li>Use GreenNexa only for lawful facility management activities.</li>
                  <li>Do not attempt to overload or disrupt the platform.</li>
                  <li>Do not inject false or malicious sensor data.</li>
                  <li>Do not use GreenNexa to monitor individuals without proper authorisation.</li>
                  <li>Do not use AI outputs to make decisions that could harm people or property without human review.</li>
                </ul>
              </Section>

              <Section title="8. Service Limitations">
                <p>
                  GreenNexa is provided on an &quot;as available&quot; basis. We do not guarantee uninterrupted
                  service. The platform may be updated, modified or temporarily unavailable for maintenance.
                  Features described as &quot;planned&quot; or &quot;demo&quot; are not guaranteed to be available
                  in any specific timeframe.
                </p>
              </Section>

              <Section title="9. Intellectual Property">
                <p>
                  The GreenNexa name, logo, design, software and documentation are the intellectual property
                  of GreenNexa. You may not copy, reproduce or redistribute any part of the platform
                  without written permission. Your organisation&apos;s data remains your property.
                </p>
              </Section>

              <Section title="10. Termination">
                <p>
                  GreenNexa reserves the right to suspend or terminate accounts that violate these terms.
                  Super Admins may deactivate organisations through the platform. Upon termination, access
                  to the platform is revoked. Data retention following termination is governed by the
                  Privacy Policy.
                </p>
              </Section>

              <Section title="11. Contact">
                <p>
                  For questions about these terms, please contact GreenNexa through the Contact page.
                  Contact details are configured by the project owner.
                </p>
              </Section>

            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className={styles.section}>
      <h2 className={styles.sectionTitle}>{title}</h2>
      <div className={styles.sectionBody}>{children}</div>
    </div>
  );
}
